### ISSUE TITLE
Invalid non-literal value for unit attribute

### ISSUE THREAD

**Issue by tbeu** [DLR-SR/ThermofluidStream#24]
Some of the sensors utilize a non-literal value fo the unit attribute, e.g., https://github.com/DLR-SR/ThermofluidStream/blob/5d41aa6517b16410cbaeb46597419dcf6ebd5888/ThermofluidStream/Sensors/MultiSensor_Tpm.mo#L41-L43
AFAIK this is not compliant with the MLS.

**Comment by dzimmer** [comment]
Ok we have to see about this. Thanks.
Just one general side-remark: If you want, feel free to open a new issue "Compatibility to SimulationX". I am extending the tool compatibility section in the readme and we would then reference to the corresponding issues.

**Comment by tbeu** [comment]
> Just one general side-remark: If you want, feel free to open a new issue "Compatibility to SimulationX". I am extending the tool compatibility section in the readme and we would then reference to the corresponding issues.

I am no longer connected with SimulationX but still interested in Modelica compliance of sophisticated Modelica libraries.

**Comment by dzimmer** [comment]
Although it probably is against the MLS, we could not bring ourselves to remove this useful part.  So far, it did not create any issues regarding tool support. 
We may reopen in case serious compatiblity issues arise or a better alternative is presented.

**Comment by tbeu** [comment]
Hm, you might mark this issue as wontfix. Feels strange otherwise.

**Comment by RaphaelGebhart** [comment]
Reopened for discussion.

I would appreciate staying compliant with the Modelica Language Specification. I believe there is a way to preserve the current functionality while still using literal values for the `unit` attribute.

One possible approach is to restructure models as follows for example for `ThermofluidStream.Sensors.Internal.GetQuantityBlock`:


```
  output Real value;
  Medium.Temperature T annotation(
    HideResult = quantity == not Types.Quantities.T_K);
  Modelica.Units.NonSI.Temperature_degC T_degC annotation(
    HideResult = quantity == not Types.Quantities.T_C);
  Medium.AbsolutePressure p annotation(
    HideResult = quantity == not Types.Quantities.p_Pa);
  Modelica.Units.NonSI.Pressure_bar p_bar annotation(
    HideResult = quantity == not Types.Quantities.p_bar);
equation 
  T = if quantity == Types.Quantities.T_K then Medium.temperature(state) else 0;
  T_degC = if quantity == Types.Quantities.T_C then Modelica.Units.Conversions.to_degC(Medium.temperature(state)) else 0;
  p = if quantity == Types.Quantities.p_Pa then Medium.pressure(state) else 0;
  p_bar = if quantity == Types.Quantities.p_bar then Modelica.Units.Conversions.to_bar(Medium.pressure(state)) else 0;
  
  if quantity == Types.Quantities.T_K then
    value = T;
  elseif quantity == Types.Quantities.T_C then
    value = T_degC;
  elseif quantity == Types.Quantities.p_Pa then
    value = p;
  else // quantity == Types.Quantities.p_bar then
    value = p_bar;
  end if;

```

The idea is to introduce explicitly typed intermediate variables (T, T_degC, p, p_bar, etc.) instead of relying on a single polymorphic `value` with conditional unit handling.


- Each physical quantity is represented as its own variable with a fixed unit annotation
- Medium functions are only called when needed. This avoids evaluating medium functions for unsupported quantities, see #282 
- Unused variables are hidden via `HideResult`

@tbeu Would you consider this a viable way to resolve the issue?

**Comment by tbeu** [comment]
Hm, not sure actually if this will work in all Modelica tools. I also question why it should be necessary to support different units (SI, Non-SI) directly in one block. If user is interested in other units, he/she can use conversion blocks of MSL to do so.

**Comment by RaphaelGebhart** [comment]
Thanks for the clarification.

My understanding was that the original trigger of the issue was the constraint on non-literal unit attributes. From the discussion, however, it seems that the broader concern is actually related to library design choices, in particular:

1. the use of non-SI units within the sensor interface  
2. the representation of multiple unit variants within a single sensor model (e.g. `ThermofluidStream.Sensors.SingleSensorSelect`)

If that interpretation is correct, it might be worth opening a separate issue for those points.

Regarding the original technical point: is the constraint on non-literal unit attributes still a concern on your side @tbeu? If so, I would still suggest testing the proposed change, as it should resolve the issue while preserving the current functionality.

As a general remark, I would also tend to prefer a clearer separation between:

- sensor models with SI-consistent outputs (one physical quantity per model)  
- display models, using user-friendly, potentially non-SI units  

However, I also understand that this would be a larger refactoring effort and that the current approach is already widely used and accepted. (Most users would be against removing the current sensors).

**Comment by tobiasreischl** [comment]
Thanks for reporting this. I rechecked the issue against the current Modelica specification and the current implementation.

The `unit` attribute does not need to be a string literal. It needs to be evaluable during translation. The unit selector parameters used here have literal default values and `annotation(Evaluate=true)`, so declarations such as

```modelica
output Real p(
  final quantity="Pressure",
  final unit=pressureUnit);
```

are valid with the current implementation.

Therefore, I do not think a code change is required for the original issue anymore.

There is, however, a separate inconsistency in `MultiSensor_Tpm`:

```modelica
Modelica.Blocks.Interfaces.RealOutput m_flow_out(
  unit="kg/s") = m_flow if outputMassFlowRate;
```

When `massFlowUnit="(g/s)"`, the numerical value of `m_flow` is converted to g/s, while the connector still declares `kg/s`.

This could be fixed separately with:

```diff
-  Modelica.Blocks.Interfaces.RealOutput m_flow_out(unit="kg/s") = m_flow if outputMassFlowRate
+  Modelica.Blocks.Interfaces.RealOutput m_flow_out(
+    final quantity="MassFlowRate",
+    final unit=massFlowUnit) = m_flow if outputMassFlowRate
```

I would therefore suggest closing this issue as no longer applicable in its original form and handling the `m_flow_out` unit mismatch in a separate commit or issue.

**Comment by RaphaelGebhart** [comment]
Closed as suggested.
