### ISSUE TITLE
Potential wrong Reference within laminarTurbulentPressureLoss.mo / Error 

### ISSUE THREAD

**Issue by Flauipaui** [DLR-SR/ThermofluidStream#30]
While checking the different pressure loss models I have recognized that the given reference 

// chang 2008. Formulas for Friction Factor in Transitional Regimes. Journal of Hydraulic Engineering. 

within laminarTurbulentPressureLosse.mo (line 54) is potentially wrong. 

I guess you mean ChEng 2008 with DOI: 10.1061/(ASCE)0733-9429(2008)134:9(1357)

Please check the reference. 

bests,

**Comment by Flauipaui** [comment]
after further examining the pressure losses according to Cheng 2008 and your implementation, it seems to be the case the the equation to compute lambda in line 57 might be wrong check with Cheng 2008 eqn 8

**Your Library**: lambda := (64/Re)^a * (1.8*log10(Re/6.8))^(2*(a-1)*b) * (2*log10(3.7*2*r/ks))^(2*(a-1)*(1-b));

**Cheng 2008**: lambda := (64/Re)^a * (1.8*log10(Re/6.8))^(2*(a-1)*b) * (2*log10(3.7*2*r/ks))^(2* **(1-a)** *(1-b)); 

Further, could it be the case that with your implementation of the friction coefficient the pressure-losses according to the Darcy-Weisbach equation would need to be implemented like this ?

Pressure Losses pressureLoss :=sign(m_flow)* **1/lambda** *l/(2*r)*rho/2*u^2;

Bests,

**Comment by mimeissner** [comment]
Thanks for your work on our library. 

I will fix the reference. 

Regarding the error in the formulas: 
Cheng computes **1/lambda** := (**Re/64**)^a * (1.8log10(Re/6.8))^(2 **(1-a)** b) * (2log10(3.72r/ks))^(2* **(1-a)** *(1-b));
Since we want lambda we compute **lambda**  := (**64/Re**)^a * (1.8log10(Re/6.8))^(2 **(a-1)** b) * (2log10(3.72r/ks))^(2* **(a-1)** *(1-b));
This also explains that we use the computed lambda instead of the reciprocal in computing the pressure loss. 

After some discussion, we will improve the normalization as well as the documentation for this function soon.

**Comment by mimeissner** [comment]
I updated the formulas for lambda calulation to avoid the if-else and added some documentation in 799c8c17ef3b9c27f3c3a3093f762c1a6ff1291f
