### ISSUE TITLE
Nozzle Test - Solving Issues - controversial output

### ISSUE THREAD

**Issue by Flauipaui** [DLR-SR/ThermofluidStream#39]
Hello, 

i was paying around with the given nozzle test that you have provided in your library. I have found a "in my eyes" controversial output of OpenModelica with cetain parameters. 

The used parameters can be seen here: https://github.com/Flauipaui/ThermofluidStream/blob/Modification/OwnTests/NozzleTest.mo

The controversial part is that Modelica seems to have problems solving and is warning the user. At the same time it is concluding that the simulation has finished successfully, see below:

The arguments x_min and x_max to OneNonLinearEquation.solve(..)
do not bracket the root of the single non-linear equation:
  x_min  = 200
  x_max  = 6000
  y_zero = 193011
  fa = f(x_min) - y_zero = 7132.07
  fb = f(x_max) - y_zero = 7.32509e+06
fa and fb must have opposite sign which is not the case.
### STATISTICS ###
The simulation finished successfully.

I'm at this state not sure if the problems is at TFSL or OpenModelica's side, maybe you could enlight me?

Bests,

**Comment by mimeissner** [comment]
Hi, 

these kinds of warnings should be fine to ignore. 

My guess is, that solving the non-linear equation fails, and therefore the solver rejects the step, retries with a reduced step-size, then succeeds in solving the equation, and continues. In Dymola this even happens multiple times at the beginning of the simulation. 
Do to your choice of parameters the fluid rapidly changes its thermodynamic state in the beginning, before fastly reaching the steady-state solution, forcing a very small step-size. Decreasing the tolerance or the output interval in the experiment annotation of your model removed the warning for me, likely due to the fact that these force the solver into a smaller step-size from the beginning. 

Two remarks to your model: firstly, due to your boundary condition, you have a prolonged reverse flow condition. For this condition we aim for robust, but not nessesarily physically correct behavior of our components. If you expect prolonged reverse flow, be advised to use the undirected components (although there is not yet a implementation of undirected dynamic flow components). Secondly, you should make sure that the area of the outlet and the inlet of any given component is the same, otherwise the simulation might behave very in a strange manner. In your example the areas of the outlet of the nozzle and the inlet of the dynamicPressureOutflow are different. 

Does this answer close the issue for you? 

Best,

**Comment by Flauipaui** [comment]
Hi, 

thank you for your reply and the detailed information on why the "error" message was given by OpenModelica. I'll close the issue.

Even more thanks for the remarks about the given model. It was ment for testing purposes only, thus no physicallity needed. I have not yet experienced strange behavior with different inlet/outlet areas between connected components. Thanks for the warning. I'll make sure that the areas will match in future. 

Bests,
