### ISSUE TITLE
Handling of Medium in OMEdit / Integration into dropofCommons

### ISSUE THREAD

**Issue by Flauipaui** [DLR-SR/ThermofluidStream#43]
Hello, 

i'm using OMEdit to run your library. While creating new models with you library i have experienced that i have to manually reference the media model to every component with "replacable package Medium = Medium". This can be annoying depending on the amount of components. 

To increase modeling convenience, i'm wondering if it could be possible to integrate the medium handling into the dropofCommons (e.g. with a drop down menu), such that the components automatically know the medium.

In case a model is dealing with several fluids it could be possible that the dropofCommons is "holding" several materials e.g. Medium1: MyMedia.Air.DryAirNasa and Medium2: MyMedia.Air.MoistAir. The user could than chose in the GUI of a component (e.g.: source) the Medium Number, close to as you have done it with the splitter componentes where you have to reference the output port numbers.

I'm looking forward hearing you opinion on that.

Bests,

**Comment by mimeissner** [comment]
We were considering such a solution, but dismissed it do tue its additional complexity that it would introduce to each model. We may consider it for a future release, so im flagging this issue as a enhancement. 
Feel free to suggest an implementation, if you want. 

Replaceable support is still new in OMEdit, you have to enable it in the settings (see https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#omedit-options-general). This could improve your workflow by a bit.

**Comment by dzimmer** [comment]
Using a world model has been considered multiple times in Modelica meetings but the language does not support that replacements can be specified at a world model. So it is technically infeasible (unfortunately).
I may remark that many tools allow to select multiple components and set ther common parameters. This is often an adequate way to set the medium. 
Situation is known to be non-ideal for Modelica.Fluid since a decade. We will improve a library when a better solution is enabled but at the moment we have to leave it as it is.
