### ISSUE TITLE
Not possible to leave fluid port unconnected 

### ISSUE THREAD

**Issue by fournien** [DLR-SR/ThermofluidStream#60]
In the process of elaborating a stratified tank based on the volumes from the library, I am missing the possibility to have fluid ports which could be left unconnected, while it is possible when using the Modelica.Fluid.Vessels.ClosedVolume for example.
The error message obtained is: The problem is structurally singular.

**Comment by dzimmer** [comment]
Please note that the outflow of volumes can be disabled by a parameter. This is in principal the cleaner way of doing it. You may study Internal.PartialVolume for this.
In your case the structural singularity might be avoidable. We investigate...

**Comment by dzimmer** [comment]
I've done some investigation:
- Unconnected outlets (for volumes) work without a problem (as expected)
- Unconnected inlets cause a structural singularity (also as expected). Here one has to work with either dummy inputs or conditional connectors.

Let me explain:
An inlet expects the thermodynamic state as input. Even if the input is then not practically used because the mass-flow is zero, the information needs to be provided. The easist way to achieve that is by a dummy input source (could be a useful component for the base library)
The dummy input source would define the mass flow to be zero, and define the default values for the thermodynamic state. The inertial pressure would be left open. 

As first test, I propose to see if the thing works if you connect each open inlet to one such dummy source each. This is then at least a check of feasibility. 
In the next step, you can then think about conditional connectors. You have the complication that you need an array of conditional connectors. That could cause some complications.... 

Why does it work at the IBSA? IBSA is using stream connectors. If they are left open they are using a default value for the inlet stream (this was added once to the spec). The use of defaults for open inputs however is not supported by Modelica (there are pros and cons). Here one shall work with conditional connectors. Which is usually easy but you have the array complification...
