### ISSUE TITLE
Unknown annotation 'experiment_X'

### ISSUE THREAD

**Issue by tobolar** [DLR-SR/ThermofluidStream#74]
In examples of `ThermofluidStream.Media.myMedia.Examples`, there is used the annotation `experiment_X` which actually is Modelica-unknown.

It shall be either 
1. deleted or
2. replaced by the `experiment` annotation - which seems to be reasonable for simulatable models.

**Comment by nieweber** [comment]
We changed the `experiment` annotation to `experiment_X` to exclude those models from regression testing. This mostly concerns the test models from external media libraries, because we usually keep them untouched. Of course we could also delete the annotation, but this would delete the simulation setup parameters of the respective models?

**Comment by beutlich** [comment]
It should be a proper [vendor-specific annotation](https://specification.modelica.org/maint/3.6/annotations.html#vendor-specific-annotations), e.g. `__DLR_experiment_X`.

**Comment by tobolar** [comment]
Principally, a package called "Examples" shall be intended to collect examples which demonstrate behaviour of models. Thus, they should indeed be simulatable.
If this is not the intention, the package sould be renamed.

Yet another possibility: there are several packages called "Tests" in the library. It seems they are not necessarilly intended like examples for users. They could be all collected into a separate library ("ThermofluidSystemsTest" - simular to "ModelicaTest"). Then `TFS.Media.myMedia.Examples` could be moved there as well.
